### ISSUE TITLE
Github Pages Deployment Failed 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [GourieJagtap/Stop-Watch#1]
**Hey Gourie !!** 
When you try to deploy some website on GitHub pages there must be an `index.html` file in your root directory. 

### What changes you should do ?
- Rename `stopwatch.html` to `index.html`
- Make sure you update all paths related to it.

**Comment by GourieJagtap** [comment]
OKAY!! I'll change it .Thanks!!!
